#pragma warning(disable : 4996)

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <valkoria/db.h>
#include <valkoria/logger.h>
#include <valkoria/type.h>
#include <extend/string.h>

int connect_database(const char *_Filename)
{
  FILE *db = fopen(_Filename, "r");
  if (db != NULL)
  {
    fclose(db);
  }
  else
  {
    Logger.log(LOG_LEVEL_INFO, "[ValkoriaDB] Database file not found. Creating new database file.");

    FILE *new_db = fopen(_Filename, "w");

    if (new_db == NULL)
    {
      return 1;
    }

    fclose(new_db);
  }

  return 0;
}

int load_database(const char *_Filename, BankDB *bankDB)
{
  Logger.log(LOG_LEVEL_INFO, "[ValkoriaDB] Loading database from file.");
  FILE *db_file = fopen(_Filename, "r");

  if (!db_file)
  {
    Logger.log(LOG_LEVEL_ERROR, "[ValkoriaDB] Failed to open database file.");
    return 1;
  }

  Account *accounts = NULL;
  size_t capacity = 0, length = 0;

  char line[MAX_LINE_LENGTH];
  Section section = SECTION_NONE;

  Account current_account = {0};

  while (fgets(line, sizeof line, db_file))
  {
    char *s = trim(line);
    if (*s == '\0' || *s == '#')
      continue; /* skip empty and comment lines */

    if (streq(s, "[Account]"))
    {
      section = SECTION_ACCOUNT;
      current_account.id[0] = '\0';
      current_account.name[0] = '\0';
      current_account.balance = 0.0;
      continue;
    }

    if (streq(s, "[End]"))
    {
      if (section == SECTION_ACCOUNT)
      {
        if (length + 1 > capacity)
        {
          capacity = capacity ? capacity * 2 : 8;
          accounts = realloc(accounts, capacity * sizeof *accounts);
          if (!accounts)
          {
            Logger.log(LOG_LEVEL_ERROR, "[ValkoriaDB] Memory allocation failed while loading accounts.");
            fclose(db_file);
            return 2;
          }
        }
        accounts[length++] = current_account;
      }
      section = SECTION_NONE;
      continue;
    }

    /******************************************************************************
     *                        Account Section Proccessing                         *
     ******************************************************************************/

    if (section == SECTION_ACCOUNT)
    {
      char *eq = strchr(s, '=');
      if (!eq)
        continue;
      *eq = '\0';
      char *key = trim(s);
      char *val = trim(eq + 1);
      if (streq(key, "id"))
      {
        strncpy(current_account.id, val, sizeof(current_account.id) - 1);
        current_account.id[sizeof(current_account.id) - 1] = '\0';
      }
      else if (streq(key, "name"))
      {
        strncpy(current_account.name, val, sizeof(current_account.name) - 1);
        current_account.name[sizeof(current_account.name) - 1] = '\0';
      }
      else if (streq(key, "balance"))
      {
        current_account.balance = strtod(val, NULL);
      }
    }
  }

  fclose(db_file);

  bankDB->num_account = length;
  bankDB->accounts = accounts;
  bankDB->num_transaction = 0;
  bankDB->transactions = NULL;

  return 0;
}

int save_database(const char *_Filename, const BankDB *bankDB)
{
  FILE *db_file = fopen(_Filename, "w");

  if (!db_file)
  {
    Logger.log(LOG_LEVEL_ERROR, "[ValkoriaDB] Failed to open database file for saving.");
    return 1;
  }

  fprintf(db_file, "# Valkoria Database File\n");
  fprintf(db_file, "# Generated by Valkoria DB\n\n");

  for (size_t i = 0; i < bankDB->num_account; i++)
  {
    const Account *account = &bankDB->accounts[i];
    fprintf(db_file, "[Account]\n");
    fprintf(db_file, "id = %s\n", account->id);
    fprintf(db_file, "name = %s\n", account->name);
    fprintf(db_file, "balance = %.2f\n", account->balance);
    fprintf(db_file, "[End]\n\n");
  }

  for (size_t i = 0; i < bankDB->num_transaction; i++)
  {
    const Transaction *transaction = &bankDB->transactions[i];
    fprintf(db_file, "[Transaction]\n");
    fprintf(db_file, "id = %s\n", transaction->id);
    fprintf(db_file, "from_id = %s\n", transaction->from_id);
    fprintf(db_file, "to_id = %s\n", transaction->to_id);
    fprintf(db_file, "amount = %.2f\n", transaction->amount);
    fprintf(db_file, "message = %s\n", transaction->message);
    fprintf(db_file, "type = %d\n", transaction->type);
    fprintf(db_file, "[End]\n\n");
  }

  fclose(db_file);

  return 0;
}

ClassDB DBC = {
    .connect = connect_database,
    .load = load_database,
    .save = save_database,
};
